spring:
    application:
        name: dfjinxin-test
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848

server:
    port: 8003 #启动端口

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false